### ISSUE TITLE
Teach the optimizer that certain refcounts never hit zero

### ISSUE THREAD

**Issue by kmod** [nitrousjit/nitrous#26]
Not sure how much this happens in larger benchmarks, but in smaller ones we see a lot of decref operations on constants that we know live through the entire program.  For example: True False None NotImplemented small_ints cython-module-constants

I imagine this working similarly to addJitConsts, but maybe phrased as addJitNonnegatives

**Comment by undingen** [comment]
If think this would work good together with defining `Py_INCREF`as `__builtin_assume(((PyObject *)(op))->ob_refcnt > 0), ((PyObject *)(op))->ob_refcnt++)` to catch a few more cases.

This should handle the general case but will fail to work for many cases (e.g. if the object escapes) but it catches some cases.

**Comment by kmod** [comment]
I worry a bit about whether the optimizer can prove that the `assume` is still valid when the decref happens; or maybe that's just another way of saying I worry that the objects will escape.  I originally wanted this for global constants, which sort of by definition have escaped already.
